server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/urarav/springcloud-config.git #GitHub上Git仓库的名字
          search-paths:
            - springcloud-config #搜索目录
      label: master #读取分支

  #RabbitMQ相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#服务注册到Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

#RabbitMQ相关配置，暴露bus刷新配置的端点：http://localhost:3344/actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
