#Consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-payment-service
  # Consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        hostname: 12.0.0.1