server:
  port: 9527

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                   # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh               # 路由的 ID，没有固定规则但要求唯一
#          uri: http://localhost:8001      # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/select/**     # 断言，路径相匹配的进行路由
        - id: payment_routh2              # 路由的 ID，没有固定规则但要求唯一
#          uri: http://localhost:8001      # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          filters:
            - AddRequestHeader=X-Request-Id, 1024
          predicates:
            - Path=/payment/port/**       # 断言，路径相匹配的进行路由
            - After=2021-06-05T14:10:55.257+08:00[Asia/Shanghai]
#            - Before=2021-06-05T14:10:55.257+08:00[Asia/Shanghai]
#            - Between=2021-06-05T14:10:55.257+08:00[Asia/Shanghai]
#            - Cookie=username, SunQi      #请求必须带有属性为username值为SunQi的Cookie
#            - Header=X-Request-Id, \d+    #请求头要必须含有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.sun.com
#            - Method=GET
#            - Query=username, \d+         #请求必须带有参数username并且值要为整数才能进行匹配

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/